name: apitronik_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  cool_dropdown: ^2.1.0
  flutter_svg: ^2.0.7
  logger: ^2.0.2+1
  url_launcher: ^6.1.14
  another_flushbar: ^1.12.30
  get: 4.6.6
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  sp_util: ^2.0.3
  firebase_core: ^2.19.0
  firebase_database: ^10.2.7
  flutter_local_notifications: ^16.1.0
  firebase_messaging: ^14.7.0
  flutter_native_splash: ^2.3.4
  http: ^1.1.0
  flutter_session_manager: ^1.0.3
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "FFFFFF"
  image: assets/images/splash_logo.png
  android: true
  ios: true
  web: true

flutter:
  assets:
    - android/app/src/main/res/
    - assets/images/
  fonts:
    - family: Lexend
      fonts:
        - asset: fonts/Lexend-Regular.ttf
        - asset: fonts/Lexend-Medium.ttf
        - asset: fonts/Lexend-SemiBold.ttf
        - asset: fonts/Lexend-Bold.ttf
        - asset: fonts/Lexend-ExtraBold.ttf
  uses-material-design: true
