// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4yJgeFy6e99YI_TtKwJv6VS1oHX11PvU',
    appId: '1:984716703319:web:189682c376c6b759369512',
    messagingSenderId: '984716703319',
    projectId: 'apitronik',
    authDomain: 'apitronik.firebaseapp.com',
    storageBucket: 'apitronik.appspot.com',
    measurementId: 'G-DVLLFCTRTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv2U4UENUxW3jbgjBoUP9sP7BnHZJMO-M',
    appId: '1:984716703319:android:b9a8bcc9b4cc2286369512',
    messagingSenderId: '984716703319',
    projectId: 'apitronik',
    storageBucket: 'apitronik.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGnD8671VRLWci2jTEZC_r0YixAPLuEh4',
    appId: '1:984716703319:ios:9a7fd9f9e64c7ce5369512',
    messagingSenderId: '984716703319',
    projectId: 'apitronik',
    storageBucket: 'apitronik.appspot.com',
    iosBundleId: 'com.example.apitronikApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGnD8671VRLWci2jTEZC_r0YixAPLuEh4',
    appId: '1:984716703319:ios:32d3154fe5d36b2a369512',
    messagingSenderId: '984716703319',
    projectId: 'apitronik',
    storageBucket: 'apitronik.appspot.com',
    iosBundleId: 'com.example.apitronikApp.RunnerTests',
  );
}
